version: '3.8'

services:
  web:
    build:
      context: ./ws_project_1
      dockerfile: Dockerfile
    volumes:
      - ./ws_project_1:/app
    ports:
      - "8000:8000"
    depends_on:
      - graphdb
    environment:
      - DEBUG=True
    restart: unless-stopped

  graphdb:
    image: ontotext/graphdb:10.4.0
    ports:
      - "7200:7200"
    volumes:
      - graphdb-data:/opt/graphdb/home
    environment:
      - GDB_HEAP_SIZE=2g
    restart: unless-stopped

volumes:
  graphdb-data: